@echo off
REM Auto-generated by generate_batch_files.py — do not edit manually.
REM Regenerate with: python generate_batch_files.py
"C:\Users\labadmin\AppData\Local\Programs\Python\Python313\python.exe" "C:\Users\labadmin\Documents\GitHub\freely-walking-optomotor\python\automation\monitor_and_track\monitor_and_track.py" %*
