function DATA = comb_data_across_cohorts_cond(protocol_dir)
% COMB_DATA_ACROSS_COHORTS_COND Combine behavioral data across all experiments
%
%   DATA = COMB_DATA_ACROSS_COHORTS_COND(protocol_dir) combines processed
%   behavioral data from all experiments for a single protocol, organizing
%   by strain, sex, and condition.
%
% INPUT:
%   protocol_dir - Path to results folder for a protocol
%                  e.g., '/path/to/results/protocol_27'
%
% OUTPUT:
%   DATA - Hierarchical struct organized as:
%          DATA.(strain).(sex)(cohort_idx).(condition).(data_type)
%
% STRUCT ORGANIZATION:
%   Level 1: strain name (e.g., 'jfrc100_es_shibire_kir')
%   Level 2: sex ('F' or 'M')
%   Level 3: cohort index (1, 2, 3, ...)
%   Level 4: condition name:
%            - 'meta': experiment metadata
%            - 'acclim_off1': pre-stimulus acclimation (dark)
%            - 'acclim_patt': acclimation with pattern displayed
%            - 'R1_condition_N': Rep 1, condition N
%            - 'R2_condition_N': Rep 2, condition N
%            - 'acclim_off2': post-stimulus acclimation (dark)
%   Level 5: data_type (fv_data, av_data, dist_data, etc.)
%
% DATA FIELDS PER CONDITION:
%   - Behavioral metrics: vel_data, fv_data, av_data, curv_data, dist_data, etc.
%   - Position data: x_data, y_data, heading_data, heading_wrap
%   - Stimulus info: trial_len, interval_dur, optomotor_pattern, optomotor_speed
%   - Social metrics: IFD_data, IFA_data
%
% NOTES:
%   - Automatically excludes existing DATA*.mat files
%   - Each condition includes 10s (300 frames) before stimulus onset
%   - Condition numbering matches protocol definition
%
% EXAMPLE:
%   DATA = comb_data_across_cohorts_cond('/path/to/results/protocol_27');
%   es_data = DATA.jfrc100_es_shibire_kir.F;
%   cond1_dist = es_data(1).R1_condition_1.dist_data;
%
% See also: combine_data_one_cohort, process_data_features, generate_exp_data_struct

    % Find all processed data for one protocol. 
    filelist = dir(fullfile(protocol_dir, '**/*.mat'));

    % Remove the DATA file if it already exits:
    idxToRemove = contains({filelist.name}, "DATA");
    filelist(idxToRemove) = [];

    n_files = length(filelist);
    
    % Initialise a struct 'DATA' to store data in. 
    DATA = struct();
    
    for idx = 1:n_files
        
        fname = filelist(idx).name;
        disp(fname)
        f_folder = filelist(idx).folder; 
    
        % Load 'comb_data', 'LOG', and 'n_fly_data' that was generated by
        % `combine_data_one_cohort` within `process_data_features`.
        load(fullfile(f_folder, fname), 'comb_data', 'LOG', 'n_fly_data');

        % Get key information about strain and sex:
        strain = LOG.meta.fly_strain;
        strain = check_strain_typos(strain);
        strain = strrep(strain, '-', '_');

        sex = LOG.meta.fly_sex;
    
        %% Extract all of the data from the entire experiment:
        % [comb_data, feat, trx] = combine_data_one_cohort(feat, trx);
    
        if isfield(DATA, strain)
                if isfield(DATA.(strain), sex)
                    sz = length(DATA.(strain).(sex))+1;
                else
                    sz = 1;
                end 
        else 
            sz = 1; 
        end 

        %% Start filling in the struct.
        DATA.(strain).(sex)(sz).meta = LOG.meta;
        DATA.(strain).(sex)(sz).meta.n_flies_arena = n_fly_data(1);
        DATA.(strain).(sex)(sz).meta.n_flies = n_fly_data(2);
        DATA.(strain).(sex)(sz).meta.n_flies_rm = n_fly_data(3);
    
        %% Add data from acclim_off1
        Log = LOG.acclim_off1;
        start_f = Log.start_f(1);
        if start_f ==0 
            start_f = 1;
        end 

        if Log.stop_t(end)<3
            stop_f = 600; %
        else
            stop_f = Log.stop_f(end);
        end

        DATA.(strain).(sex)(sz).acclim_off1.vel_data = comb_data.vel_data(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_off1.fv_data = comb_data.fv_data(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_off1.dist_data = comb_data.dist_data(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_off1.dist_trav = comb_data.dist_trav(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_off1.av_data = comb_data.av_data(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_off1.curv_data = comb_data.curv_data(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_off1.heading_data = comb_data.heading_data(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_off1.heading_wrap = comb_data.heading_wrap(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_off1.x_data = comb_data.x_data(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_off1.y_data = comb_data.y_data(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_off1.view_dist = comb_data.view_dist(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_off1.IFD_data = comb_data.IFD_data(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_off1.IFA_data = comb_data.IFA_data(:, start_f:stop_f);
    
        %% Add data from acclim_patt
        Log = LOG.acclim_patt;
        start_f = Log.start_f(1);
        stop_f = Log.stop_f(end);
        DATA.(strain).(sex)(sz).acclim_patt.vel_data = comb_data.vel_data(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_patt.fv_data = comb_data.fv_data(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_patt.dist_data = comb_data.dist_data(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_patt.dist_trav = comb_data.dist_trav(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_patt.av_data = comb_data.av_data(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_patt.curv_data = comb_data.curv_data(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_patt.heading_data = comb_data.heading_data(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_patt.heading_wrap = comb_data.heading_wrap(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_patt.x_data = comb_data.x_data(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_patt.y_data = comb_data.y_data(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_patt.view_dist = comb_data.view_dist(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_patt.IFD_data = comb_data.IFD_data(:, start_f:stop_f);
        DATA.(strain).(sex)(sz).acclim_patt.IFA_data = comb_data.IFA_data(:, start_f:stop_f);

        % Find out how many unique conditions there are:
        fields = fieldnames(LOG);
        logfields = fields(startsWith(fields, 'log_'));
        n_cond = height(logfields);

        %% Then run through the conditions: 
        for log_n = 1:n_cond
    
            Log = LOG.(logfields{log_n});

            if log_n <(n_cond/2)+1
                rep_str = 'R1_condition_';
            else
                rep_str = 'R2_condition_';
            end 

            condition_n = Log.which_condition;

            % if ismember(condition_n, [1,2,9,10])
                if LOG.acclim_off1.stop_t(end)<3 && log_n == 1
                    framesb4 = 0;
                else
                    framesb4 = 300;
                end
    
                start_f = Log.start_f(1)-framesb4;
                stop_f = Log.stop_f(end);
    
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).trial_len = Log.trial_len;
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).interval_dur = Log.interval_dur;
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).optomotor_pattern = Log.optomotor_pattern;
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).optomotor_speed = Log.optomotor_speed;
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).interval_pattern = Log.interval_pattern;
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).interval_speed = Log.interval_speed;
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).start_flicker_f = Log.start_f(end)-start_f;
    
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).vel_data = comb_data.vel_data(:, start_f:stop_f);
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).fv_data = comb_data.fv_data(:, start_f:stop_f);
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).dist_data = comb_data.dist_data(:, start_f:stop_f);
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).dist_trav = comb_data.dist_trav(:, start_f:stop_f);
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).av_data = comb_data.av_data(:, start_f:stop_f);
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).curv_data = comb_data.curv_data(:, start_f:stop_f);
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).heading_data = comb_data.heading_data(:, start_f:stop_f);
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).heading_wrap = comb_data.heading_wrap(:, start_f:stop_f);
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).x_data = comb_data.x_data(:, start_f:stop_f);
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).y_data = comb_data.y_data(:, start_f:stop_f);
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).view_dist = comb_data.view_dist(:, start_f:stop_f);
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).IFD_data = comb_data.IFD_data(:, start_f:stop_f);
                DATA.(strain).(sex)(sz).(strcat(rep_str, string(condition_n))).IFA_data = comb_data.IFA_data(:, start_f:stop_f);
            % end 
        end 
    
        %% Add data from acclim_off2
        Log = LOG.acclim_off2;
        start_f = Log.start_f(1);
        % stop_f = Log.stop_f(end); % Could use the actual last frame
        % instead of "end".
        DATA.(strain).(sex)(sz).acclim_off2.vel_data = comb_data.vel_data(:, start_f:end);
        DATA.(strain).(sex)(sz).acclim_off2.fv_data = comb_data.fv_data(:, start_f:end);
        DATA.(strain).(sex)(sz).acclim_off2.dist_data = comb_data.dist_data(:, start_f:end);
        DATA.(strain).(sex)(sz).acclim_off2.dist_trav = comb_data.dist_trav(:, start_f:end);
        DATA.(strain).(sex)(sz).acclim_off2.av_data = comb_data.av_data(:, start_f:end);
        DATA.(strain).(sex)(sz).acclim_off2.curv_data = comb_data.curv_data(:, start_f:end);
        DATA.(strain).(sex)(sz).acclim_off2.heading_data = comb_data.heading_data(:, start_f:end);
        DATA.(strain).(sex)(sz).acclim_off2.heading_wrap = comb_data.heading_wrap(:, start_f:end);
        DATA.(strain).(sex)(sz).acclim_off2.x_data = comb_data.x_data(:, start_f:end);
        DATA.(strain).(sex)(sz).acclim_off2.y_data = comb_data.y_data(:, start_f:end);
        DATA.(strain).(sex)(sz).acclim_off2.view_dist = comb_data.view_dist(:, start_f:end);
        DATA.(strain).(sex)(sz).acclim_off2.IFD_data = comb_data.IFD_data(:, start_f:end);
        DATA.(strain).(sex)(sz).acclim_off2.IFA_data = comb_data.IFA_data(:, start_f:end);
    
    end 

    % Save 'DATA' - this is currently commented out because the struct were
    % becoming > 2GB and so couldn't be saved.
    % todaysdate =  string(datetime('now', 'Format','yyyy-MM-dd'));
    % save(string(fullfile(protocol_dir, strcat(protocol, '_DATA_', todaysdate, '.mat'))), 'DATA');

end 
