"""
Generate .bat launcher files for automation scripts.

Reads PYTHON_EXE and REPO_ROOT from config so batch files don't contain
hardcoded paths. Run this after setting up a new machine.

Usage:
    python generate_batch_files.py
"""

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from config.config import PYTHON_EXE, REPO_ROOT

AUTOMATION_DIR = REPO_ROOT / "python" / "automation"

BAT_TEMPLATE = """@echo off
REM Auto-generated by generate_batch_files.py — do not edit manually.
REM Regenerate with: python generate_batch_files.py
"{python_exe}" "{script_path}" %*
"""

SCRIPTS = [
    {
        "bat_dir": AUTOMATION_DIR / "monitor_and_copy",
        "bat_name": "run_monitor_and_copy.bat",
        "script": AUTOMATION_DIR / "monitor_and_copy" / "monitor_and_copy.py",
    },
    {
        "bat_dir": AUTOMATION_DIR / "monitor_and_track",
        "bat_name": "run_monitor_and_track.bat",
        "script": AUTOMATION_DIR / "monitor_and_track" / "monitor_and_track.py",
    },
    {
        "bat_dir": AUTOMATION_DIR / "daily_processing",
        "bat_name": "run_daily_processing.bat",
        "script": AUTOMATION_DIR / "daily_processing" / "daily_processing.py",
    },
]


def main():
    for entry in SCRIPTS:
        bat_path = entry["bat_dir"] / entry["bat_name"]
        content = BAT_TEMPLATE.format(
            python_exe=str(PYTHON_EXE),
            script_path=str(entry["script"]),
        ).lstrip("\n")

        with open(bat_path, "w", newline="\r\n") as f:
            f.write(content)

        print(f"Generated: {bat_path}")

    print("\nBatch files generated. They use:")
    print(f"  Python: {PYTHON_EXE}")
    print(f"  Repo:   {REPO_ROOT}")
    print("\nNote: %* passes any CLI arguments through (e.g., --reprocess, --timeout 0)")


if __name__ == "__main__":
    main()
